import YAML from "yaml";
import type { AgentArtifacts, Finding, McpScanResult, RepoProfile } from "../types.js";

export function generateArtifacts(
  profile: RepoProfile,
  mcp: McpScanResult,
  findings: Finding[]
): AgentArtifacts {
  return {
    agentsMd: generateAgentsMd(profile, findings),
    cursorRule: generateCursorRule(profile),
    copilotInstructions: generateCopilotInstructions(profile),
    contextMap: generateContextMap(profile, mcp, findings),
    mcpPolicy: generateMcpPolicy(mcp),
    githubAction: generateGitHubAction()
  };
}

function generateAgentsMd(profile: RepoProfile, findings: Finding[]): string {
  const commands = profile.commands.length
    ? profile.commands.map((command) => `- ${command.name}: \`${command.command}\` (${command.source})`).join("\n")
    : "- No test/build commands were detected. Ask before inventing commands.";
  const sourceDirs = profile.sourceDirs.length ? profile.sourceDirs.map((dir) => `\`${dir}/\``).join(", ") : "not detected";
  const entrypoints = formatInlineFiles(profile.entrypoints ?? []);
  const risky = findings
    .filter((finding) => finding.severity === "critical" || finding.severity === "high")
    .slice(0, 6)
    .map((finding) => `- ${finding.title}${finding.file ? ` in \`${finding.file}\`` : ""}`)
    .join("\n");

  return `# Agent Instructions

This repository is prepared for AI coding agents by repo-agent-kit.

## Project Snapshot

- Name: ${profile.name}
- Primary languages: ${formatObject(profile.languages)}
- Frameworks: ${profile.frameworks.length ? profile.frameworks.join(", ") : "not detected"}
- Entrypoints: ${entrypoints}
- Source directories: ${sourceDirs}
- Test directories: ${profile.testDirs.length ? profile.testDirs.map((dir) => `\`${dir}/\``).join(", ") : "not detected"}

## Commands

${commands}

## Working Rules

- Read this file before making changes.
- Prefer small, targeted patches that follow the existing project style.
- Run the narrowest relevant test command before reporting success.
- Do not edit generated, vendored, or dependency directories.
- Ask before running destructive commands, database migrations, deployment commands, or commands that access production systems.
- Do not expose secrets from .env files, private keys, local credentials, or MCP configuration.

## Agent Safety Notes

${risky || "- No critical or high-risk findings were detected in the latest scan."}

## Recommended Reading Order

${formatReadingOrder(profile)}

Generated by repo-agent-kit. Review and customize this file for project-specific architecture rules.
`;
}

function generateCursorRule(profile: RepoProfile): string {
  return `---
description: Project-level rules generated by repo-agent-kit
alwaysApply: true
---

# Project Rules

- Treat AGENTS.md as the source of truth for coding-agent behavior.
- Use detected commands instead of guessing:
${profile.commands.map((command) => `  - ${command.name}: \`${command.command}\``).join("\n") || "  - No commands detected."}
- Keep changes scoped to the requested files and related tests.
- Do not read or print local secrets, private keys, or environment files.
- Confirm before running write-heavy tools, database commands, deployment commands, or MCP tools with shell/filesystem access.
`;
}

function generateCopilotInstructions(profile: RepoProfile): string {
  return `# Copilot Instructions

This repository is configured for AI coding assistance.

- Main languages: ${Object.keys(profile.languages).join(", ") || "not detected"}
- Frameworks: ${profile.frameworks.join(", ") || "not detected"}
- Prefer these commands when validating changes:
${profile.commands.map((command) => `  - ${command.name}: \`${command.command}\``).join("\n") || "  - No commands detected."}
- Follow AGENTS.md for safety, testing, and project-specific guidance.
- Avoid exposing secrets or using MCP tools that can access shell, filesystem, cloud, or database resources without explicit approval.
`;
}

function generateContextMap(profile: RepoProfile, mcp: McpScanResult, findings: Finding[]): string {
  const riskRows = findings.length
    ? findings.slice(0, 20).map((finding) => `| ${finding.severity} | ${finding.title} | ${finding.file ?? "-"} |`).join("\n")
    : "| low | No findings detected | - |";

  return `# Agent Context Map

## Repository

- Root: \`${profile.root}\`
- Name: ${profile.name}
- Package manager: ${profile.packageManager ?? "not detected"}
- CI: ${profile.ciProviders.join(", ") || "not detected"}
- Scan strategy: ${profile.scanStrategy?.mode ?? "standard"}

## Languages

${formatBulletObject(profile.languages)}

## Frameworks

${profile.frameworks.map((framework) => `- ${framework}`).join("\n") || "- None detected"}

## Commands

${profile.commands.map((command) => `- ${command.name}: \`${command.command}\` from ${command.source}`).join("\n") || "- None detected"}

## Entrypoints

${profile.entrypoints?.map((file) => `- \`${file}\``).join("\n") || "- None detected"}

## Important Files

${profile.importantFiles.map((file) => `- \`${file}\``).join("\n") || "- None detected"}

## Scan Notes

${profile.scanStrategy?.notes.map((note) => `- ${note}`).join("\n") || "- None"}

## MCP Servers

${mcp.servers.map((server) => `- ${server.name}: ${server.transport}, tags: ${server.riskTags.join(", ") || "none"}`).join("\n") || "- No MCP servers detected"}

## Findings

| Severity | Finding | File |
| --- | --- | --- |
${riskRows}
`;
}

function generateMcpPolicy(mcp: McpScanResult): string {
  const policy = {
    version: 1,
    mode: "review-first",
    defaults: {
      allowNetwork: false,
      allowFilesystemWrite: false,
      allowShell: false,
      requireHumanApproval: ["shell", "filesystem", "database", "cloud", "secrets"]
    },
    servers: Object.fromEntries(
      mcp.servers.map((server) => [
        server.name,
        {
          transport: server.transport,
          riskTags: server.riskTags,
          decision: server.riskTags.length ? "review" : "allow"
        }
      ])
    )
  };
  return YAML.stringify(policy);
}

function generateGitHubAction(): string {
  return `name: Agent Readiness

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  repo-agent-kit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Scan repository for AI agent readiness
        run: npx repo-agent-kit scan --json > agent-readiness.json
      - uses: actions/upload-artifact@v4
        with:
          name: agent-readiness
          path: agent-readiness.json
`;
}

function formatObject(value: Record<string, number>): string {
  const entries = Object.entries(value);
  return entries.length ? entries.map(([key, count]) => `${key} (${count})`).join(", ") : "not detected";
}

function formatBulletObject(value: Record<string, number>): string {
  const entries = Object.entries(value);
  return entries.length ? entries.map(([key, count]) => `- ${key}: ${count} files`).join("\n") : "- None detected";
}

function formatInlineFiles(files: string[], maxFiles = 8): string {
  if (!files.length) {
    return "not detected";
  }
  const visible = files.slice(0, maxFiles).map((file) => `\`${file}\``).join(", ");
  const remaining = files.length - maxFiles;
  return remaining > 0 ? `${visible}, and ${remaining} more` : visible;
}

function readingOrder(profile: RepoProfile): string[] {
  return [...new Set([...profile.importantFiles.filter((file) => /^README/i.test(file)), ...(profile.entrypoints ?? []), ...profile.importantFiles])].slice(0, 8);
}

function formatReadingOrder(profile: RepoProfile): string {
  const files = readingOrder(profile);
  return files.length ? files.map((file, index) => `${index + 1}. \`${file}\``).join("\n") : "1. Project entry files";
}
